config/routes.rb
DbExplorer::Application.routes.draw do

  resources :database_connections, :except => [:show]

  get "database_connections/:id/schemas(/:name)" => "schemas#show", :as => :schemas
  get "database_connections/:id/schemas/:name" => "schemas#show", :as => :schema

  scope "abstract/:connection_id/schema/:name/" do
   resources :abstracts, controller: 'abstract_objects'
  end
  match "database_connections/:id/schemas/:name/search" => "schemas#search", :via => [:get, :post], :as => :search_schemas

  root :to => 'database_connections#index'

end

app/models/database_connection.rb
class DatabaseConnection < ActiveRecord::Base
  validates :database, :adapter, :presence => :true
  validate :existing_file, :if => :sqlite3
  validate :working_configuration

  # Retrun hash with connection configuration, for ActiveRecord
  def config
    {database: database, username: username, password: password, adapter: adapter, host: host, port: port, encoding: encoding}
  end

  def to_s
    title.present? ? title : database
  end

  private

  # Be sure the connection to DB is working before store configuration
  def working_configuration
    begin
      Schema.new(config) if errors[:database].empty?
    rescue Exception => e
      errors.add(:database, e.to_s)
      return false
    end
  end

  # Check if connection is sqlite3
  def sqlite3
    adapter == "sqlite3"
  end

  # If connection is sqlite3, be sure the file is existing
  def existing_file
    if sqlite3 && database && !File.exist?(database)
      self.errors.add(:database, :not_exist)
    end
  end

end

app/models/schema.rb
require 'digest/md5'
require 'csv'

class Schema

  def initialize(config)
    @klass = define_class(config)
    @schemas = {}
    @connection = @klass.connection
    @connection.tables.each do |table_name|
      add_to_schema(config, table_name)
    end
  end


  # Return names of all table columns
  def get_table_attributes(table_name)
    get_schemas[table_name].columns.map(&:name)
  end

  # Return names of all tables for connection
  def get_tables
     get_schemas.keys
  end

  # Return all instantiated classes (models) for connection
  def get_schemas
    @schemas
  end

  def self.to_csv(column_names, collection)
    CSV.generate do |csv|
      csv << column_names
      collection.each do |obj|
        csv << obj.attributes.values_at(*column_names)
      end
    end
  end


  private

  # Dynamicly define models (classes which inherit from ActiveRecord::Base) and set dynamicly the name of table
  def define_class(config, table_name_string = nil)
    Class.new ActiveRecord::Base do
      def self.random_name
        (0...8).map { (65 + rand(26)).chr }.join
      end

      def self.name
        @name ||= random_name.classify
      end

      establish_connection config
      self.abstract_class = false
      cattr_accessor :model_name

      if table_name_string
        self.table_name = table_name_string
        self.model_name = ActiveModel::Name.new(self, nil, table_name_string.classify)
      end

    end
  end


  # Define class for some table and push it to schemas hash
  # { "Cars" => CarClass }
  def add_to_schema(config, table_name)
    klass = define_class(config, table_name)
    @schemas[table_name] = klass
  end
end

app/controllers/abstract_objects_controller.rb
class AbstractObjectsController < ApplicationController
  inherit_resources
  defaults :instance_name => 'abstract_object'

  before_filter :setup_class

  def create
    create!{schema_path(@database_connection, name: @name)}
  end

  def update
    update!{schema_path(@database_connection, name: @name)}
  end

  def destroy
    destroy!{schema_path(@database_connection, name: @name)}
  end

  private

  def setup_class
    @database_connection = DatabaseConnection.find(params[:connection_id])
    @schema = Schema.new(@database_connection.config)
    @name = params[:name]
    @model_name = @name.humanize
    self.class.resource_class = @schema.get_schemas[@name]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_connections
  
  
  private
  
  def load_connections
    @database_connections = DatabaseConnection.all
  end
  
end

app/controllers/database_connections_controller.rb
class DatabaseConnectionsController < ApplicationController
  inherit_resources

  def create
    create!{collection_path}
  end

  def update
    update!{collection_path}
  end


  private

  def collection
    order = ActiveRecord::Base.connection.adapter_name == 'Mysql2' ? "`database_connections`.`database` ASC" : "database_connections.database ASC"
    @database_connections = DatabaseConnection.order(order).page(params[:page])
  end
end

app/controllers/schemas_controller.rb
class SchemasController < ApplicationController

  def search
    collection
    render :show
  end

  def show
    collection
    respond_to do |format|
      format.html { }
      format.csv { render text: Schema.to_csv(@columns_names, @model.all) }
    end
  end

  private

  def collection
    @database_connection = DatabaseConnection.find(params[:id])
    @schema = Schema.new(@database_connection.config)
    if @name = params[:name]
      params[:q] = get_search_params_from_session(@database_connection.id, @name)
      @columns_names = @schema.get_table_attributes(@name)
      @model = @schema.get_schemas[@name]
      @search = @model.ransack(params[:q], :engine => @model)
      @collection =  @search.result.page(params[:page]).per(get_per_page(@database_connection.id, @name))
    end
  end

  def get_search_params_from_session(connection_id, name)
    key = "search_#{connection_id}_#{name}"
    session[key] = params[:q] if params[:q]
    session[key] = nil if params[:clear_search]
    session[key]
  end

  def get_per_page(connection_id, name)
    key = "search_#{connection_id}_#{name}_per_page"
    session[key] = params[:per_page] if params[:per_page]
    session[key]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when :notice then "info"
      when :error then "error"
      when :alert then "warning"
    end
  end

  def icon(icon_type)
    content_tag(:i, '', :class => "icon-#{icon_type}")
  end

  def search_conditions_count(search_hash = {})
    count = 0
    count += search_hash[:c].keys.count if search_hash[:c]
    count += search_hash[:s].keys.count if search_hash[:s]
  end

  def setup_search_form(builder)
    content_for :document_ready, %Q{
      var search = new Search();
      $(document).on('click', 'a.add_fields', function() {
        search.add_fields(this, $(this).data('fieldType'), $(this).data('content'));
        return false;
      });
      $(document).on('click', 'a.remove_fields', function() {
        search.remove_fields(this);
        return false;
      });
    }.html_safe
  end

  def button_to_remove_fields(name, f, title = nil)
    content_tag :a, name, class: 'remove_fields btn btn-mini btn-danger', :title => title
  end

  def button_to_add_fields(name, f, type, title = nil)
    new_object = f.object.send "build_#{type}"
    fields = f.send("#{type}_fields", new_object, child_index: "new_#{type}") do |builder|
      render("/search/" + type.to_s + "_fields", f: builder)
    end
    content_tag :a, name, :class => 'add_fields btn btn-mini btn-primary', :title => title, 'data-field-type' => type, 'data-content' => "#{fields}"
  end

  def format_value(value)
    case value
    when String then truncate(value, :length => 40)
    else
      value
    end
  end

  def get_per_page(connection_id, name)
    key = "search_#{connection_id}_#{name}_per_page"
    session[key] || Kaminari.config.default_per_page
  end

end

app/views/abstract_objects/_form.html.haml
- url = @abstract_object.new_record? ? abstracts_path(connection_id: @database_connection.id, name: @name) : abstract_path(id: @abstract_object.id, connection_id: @database_connection.id, name: @name)

= simple_form_for @abstract_object, :as => "abstract_object", :url=> url, :html => { :class => 'form-horizontal' } do |f|
  - @schema.get_table_attributes(@name).each do |attr|
    = f.input attr, disabled: attr == "id"
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), schema_path(@database_connection, name: @name), :class => 'btn'

app/views/abstract_objects/edit.html.haml
%h1= t '.title', :default => t('helpers.titles.edit', :model => @model_name,:default => "Edit #{@model_name}")                                      
= render :partial => 'form'

app/views/abstract_objects/new.html.haml
%h1= t '.title', :default => t('helpers.titles.new', :model => @model_name, :default => "New #{@model_name}")                                      
= render :partial => 'form'

app/views/abstract_objects/show.html.haml
%h1= t '.title', :default => t('helpers.titles.show', :model => @model_name, :default => "#{@model_name} detail")       
%p.action-buttons
  = link_to t('.destroy', :default => t("helpers.links.destroy")),  
    abstract_path(@abstract_object, connection_id: @database_connection.id, name: @name),                                                  
    :method => :delete,                                                                             
    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), 
    :class => 'btn btn-danger pull-right'
  
  = link_to t('.edit', :default => t("helpers.links.edit")),  
    edit_abstract_path(@abstract_object, connection_id: @database_connection.id, name: @name),
    :class => 'btn btn-primary pull-right'
    
  = link_to t('.back', :default => t("helpers.links.back")), schema_path(@database_connection, name: @name),                     
    :class => 'btn pull-right'

  
%table.table
  - @schema.get_table_attributes(@name).each do |attr|
    %tr
      %th= attr
      %td= @abstract_object.send(attr)
  

app/views/database_connections/_form.html.haml
= simple_form_for @database_connection, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title, :hint => t(".title_hint")
  = f.input :adapter, :as => :select, :collection => [:sqlite3, :postgresql, :mysql2]
  = f.input :database
  = f.input :password
  = f.input :username
  = f.input :host
  = f.input :port
  = f.input :encoding, :collection => (Encoding.name_list + ["utf8"] + ["UTF8"]).sort, :selected => @database_connection.encoding || "UTF-8" 
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      database_connections_path, :class => 'btn'                   |

app/views/database_connections/edit.html.haml
- model_class = @database_connection.class
%h1= t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, |
    :default => "Edit #{model_class.model_name.human}")                                      |
= render :partial => 'form'

app/views/database_connections/index.html.haml
- model_class = DatabaseConnection.new.class

- unless @database_connections.any?

  %p.notice
    = t(".no_connection")
    = link_to(t(".new"), new_database_connection_path)
    !

- else

  %h1= t '.title', :default => model_class.model_name.human.pluralize

  = link_to t('.new', :default => t("helpers.links.new")),
    new_database_connection_path,
    :class => 'btn btn-primary pull-right'

  %table.table.table-striped
    %thead
      %tr
        %th= model_class.human_attribute_name(:title)
        %th= model_class.human_attribute_name(:database)
        %th= model_class.human_attribute_name(:adapter)
        %th= model_class.human_attribute_name(:password)
        %th= model_class.human_attribute_name(:username)
        %th= model_class.human_attribute_name(:host)
        %th= model_class.human_attribute_name(:port)
        %th= model_class.human_attribute_name(:encoding)
        %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @database_connections.each do |database_connection|
        %tr
          %td= link_to database_connection, schemas_path(database_connection)
          %td= database_connection.database
          %td= database_connection.adapter
          %td= t(".#{!database_connection.password.blank?}")
          %td= database_connection.username
          %td= database_connection.host
          %td= database_connection.port
          %td= database_connection.encoding
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")),
              edit_database_connection_path(database_connection), :class => 'btn btn-mini'

            = link_to t('.destroy', :default => t("helpers.links.destroy")),
              database_connection_path(database_connection),
              :method => :delete,
              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
              :class => 'btn btn-mini btn-danger'

  = paginate @database_connections

app/views/database_connections/new.html.haml
- model_class = @database_connection.class
%h1= t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, |
    :default => "New #{model_class.model_name.human}")                                      |
= render :partial => 'form'

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "DbExplorer"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "/"} db Explorer
          .container-fluid.nav-collapse
            %ul.nav
              - @database_connections.each do |database_connection|
                - selected = @database_connection && (database_connection == @database_connection)
                %li= link_to database_connection, schemas_path(database_connection),
                  :class =>  selected ? "selected" : ""

    .container-fluid
      - [:notice, :error, :alert].each do |level|
        - unless flash[level].blank?
          .alert{:class => flash_class(level)}
            %a.close{:href => "#", :"data-dismiss"=>"alert"} ×
            = content_tag :p, flash[level]
    .container-fluid
      %ul.nav.tables_list
        - if @schema
          %li.nav-header
            = label_tag t("list_of_tables")
            = select_tag :name, options_for_select(@schema.get_tables, @name), id: "table-list", style: "width:300px", data: {url: schemas_path(@database_connection)}, include_blank: true
      = yield
      %footer

    :javascript
        $(function() {
          #{yield :document_ready}
        });

    - if !(flash[:notice] || flash[:error] || flash[:alert]).blank?
      :javascript
        $(".alert").alert()

app/views/schemas/show.html.haml
- unless @model
  .notice=t(".no_model")
- else

  %h1= t '.title', :default => @name.humanize
  = render :partial => "search/search_form"

  = link_to t('.export', :default => t("helpers.links.export")),
      schema_path(@database_connection, name: @name, format: :csv),
      :class => 'btn btn-danger pull-right'

  - if @columns_names.include?("id")
    = link_to t('.new', :default => t("helpers.links.new")),
      new_abstract_path(@database_connection, name: @name),
      :class => 'btn btn-primary pull-right'

  %table.table-condensed.table-striped.table
    %thead
      %tr
        - @columns_names.each do |name|
          %th= name
        %th= t(".actions")

    %tbody
      - @collection.each do |res|
        %tr
          - @columns_names.each do |attr|
            %td
              - if attr == "id"
                = link_to(res.send(attr), abstract_path(res, connection_id: @database_connection.id, name: @name))
              - else
                = format_value(res.send(attr))
          %td
            - if res.respond_to?(:id) && !res.id.blank?
              = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_abstract_path(res, connection_id: @database_connection.id, name: @name), :class => 'btn btn-mini'

              = link_to t('.destroy', :default => t("helpers.links.destroy")),
                abstract_path(res, connection_id: @database_connection.id, name: @name),
                :method => :delete,
                :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                :class => 'btn btn-mini btn-danger'

  = paginate @collection
  .page-info= page_entries_info @collection
  = form_tag schema_path(@database_connection, name: @name), method: :get, class: 'form-inline' do
    = label_tag :per_page, t('.per_page', :default => t("helpers.per_page"))
    = text_field_tag :per_page, get_per_page(@database_connection.id, @name), class: "small"
    = submit_tag "Change", :class => 'btn-primary'

app/views/search/_attribute_fields.html.haml
%span.fields{"data-object-name" => f.object_name}
  = f.attribute_select associations: @model.ransackable_associations

app/views/search/_condition_fields.html.haml
%p.controls
  %span.fields.condition{"data-object-name" => f.object_name}
    = f.attribute_fields do |a|
      = render '/search/attribute_fields', f: a
    = f.predicate_select
    = f.value_fields do |v|
      = render '/search/value_fields', f: v
    =button_to_remove_fields icon("minus"), f, t("search.remove")

app/views/search/_search_form.html.haml
%a#searchToggleLink{:data => {"toggle"=> "collapse", :target => "#searchForm"}}= t(".search_and_sort")

- if params[:q]
  = "(#{search_conditions_count(params[:q])}) #{ t('.conditions_added')}"
#searchForm.collapse
  = search_form_for @search, url: search_schemas_path(@database_connection, name: @name), html: {method: :post, class: "form-horizontal"} do |f|
    - setup_search_form f
    %fieldset
      %legend
        = t("search.sorting")  
      .control-group
        = f.sort_fields do |s|
          = render '/search/sort_fields', f: s
        = button_to_add_fields icon("plus"), f, :sort, t("search.add_sort")
    %fieldset
      %legend
        = t("search.conditions")
      .control-group
        = f.condition_fields do |c|
          = render '/search/condition_fields', f: c
        = button_to_add_fields icon("plus"), f, :condition, t("search.add_condition")
  
    = f.submit(class: "btn btn-primary")
    = link_to t(".cancel"), search_schemas_path(@database_connection, name: @name, :clear_search => "1"), class: "btn"
    

app/views/search/_sort_fields.html.haml
%p.controls
  %span.fields{"data-object-name" => f.object_name}
    = f.sort_select
    = button_to_remove_fields icon("minus"), f, t("search.remove")

app/views/search/_value_fields.html.haml
%span.fields.value{"data-object-name" => f.object_name}
  = f.text_field :value